# app/core/constants.py
"""
Centralized constant values & thresholds used across services.

Having a single source makes tuning easier and avoids magic numbers
scattered throughout the codebase.
"""

# =========================
# Segmentation Service
# =========================
SEGMENTATION_INPUT_SIZE = 640
SEGMENTATION_CONF_THRESHOLD = 0.50
SEGMENTATION_IOU_THRESHOLD = 0.45
SEGMENTATION_MASK_THRESHOLD = 0.30

# Quality filtering for segments
SEGMENTATION_STD_THRESHOLD = 2.0
SEGMENTATION_MIN_AREA = 100

# Rectangle expansion constraints
RECT_EXPAND_MAX_PADDING = 50
RECT_EXPAND_PADDING_STEP = 2
RECT_EXPAND_MIN_GAP = 5
RECT_EXPAND_EDGE_MIN_COVERAGE = 0.85
RECT_EXPAND_REGION_MIN_COVERAGE = 0.95

# =========================
# Text Detection Service
# =========================
TEXT_DET_LETTERBOX_SIZE = 1024
TEXT_DET_LETTERBOX_STRIDE = 64
TEXT_DET_NMS_CONF_THRESHOLD = 0.25
TEXT_DET_NMS_IOU_THRESHOLD = 0.35
TEXT_DET_MASK_BIN_THRESHOLD = 0.30

# Global detection / filtering
TEXT_DET_GLOBAL_MIN_SCORE = 0.3
TEXT_DET_BOX_MIN_AREA = 100
TEXT_DET_BOX_MAX_AREA = 50000
TEXT_DET_BOX_MIN_ASPECT = 0.1
TEXT_DET_BOX_MAX_ASPECT = 20.0
TEXT_DET_BOX_MIN_SOLIDITY = 0.3
TEXT_DET_MERGE_DISTANCE_THRESHOLD = 50
TEXT_DET_OVERLAP_IOU_THRESHOLD = 0.7

# VIS3 filtering
VIS3_BOX_MIN_SIZE = 1500
VIS3_OCR_MAX_SIZE = 300000
VIS3_LARGE_BOX_MIN_CHARS = 10
VIS3_MIN_TEXT_DENSITY = 0.0002
VIS3_BLACKLIST_PATTERN = r'^[～．ー！？０-９~.!?0-9\\-\\s]*$'

# Image quality thresholds
IMG_QUALITY_MIN_LAPLACIAN_VAR = 100
IMG_QUALITY_MIN_CONTRAST = 15
IMG_QUALITY_MIN_BRIGHTNESS = 20
IMG_QUALITY_MAX_BRIGHTNESS = 235

# =========================
# OCR Service
# =========================
OCR_DEFAULT_CONFIDENCE = 1.0

# =========================
# Inpainting Service
# =========================
INPAINT_MIN_MASK_COVERAGE_PERCENT = 0.01
INPAINT_DEFAULT_DILATE_KERNEL = 5

__all__ = [
    # Segmentation
    "SEGMENTATION_INPUT_SIZE",
    "SEGMENTATION_CONF_THRESHOLD",
    "SEGMENTATION_IOU_THRESHOLD",
    "SEGMENTATION_MASK_THRESHOLD",
    "SEGMENTATION_STD_THRESHOLD",
    "SEGMENTATION_MIN_AREA",
    "RECT_EXPAND_MAX_PADDING",
    "RECT_EXPAND_PADDING_STEP",
    "RECT_EXPAND_MIN_GAP",
    "RECT_EXPAND_EDGE_MIN_COVERAGE",
    "RECT_EXPAND_REGION_MIN_COVERAGE",
    # Text Detection
    "TEXT_DET_LETTERBOX_SIZE",
    "TEXT_DET_LETTERBOX_STRIDE",
    "TEXT_DET_NMS_CONF_THRESHOLD",
    "TEXT_DET_NMS_IOU_THRESHOLD",
    "TEXT_DET_MASK_BIN_THRESHOLD",
    "TEXT_DET_GLOBAL_MIN_SCORE",
    "TEXT_DET_BOX_MIN_AREA",
    "TEXT_DET_BOX_MAX_AREA",
    "TEXT_DET_BOX_MIN_ASPECT",
    "TEXT_DET_BOX_MAX_ASPECT",
    "TEXT_DET_BOX_MIN_SOLIDITY",
    "TEXT_DET_MERGE_DISTANCE_THRESHOLD",
    "TEXT_DET_OVERLAP_IOU_THRESHOLD",
    "VIS3_BOX_MIN_SIZE",
    "VIS3_OCR_MAX_SIZE",
    "VIS3_LARGE_BOX_MIN_CHARS",
    "VIS3_MIN_TEXT_DENSITY",
    "VIS3_BLACKLIST_PATTERN",
    "IMG_QUALITY_MIN_LAPLACIAN_VAR",
    "IMG_QUALITY_MIN_CONTRAST",
    "IMG_QUALITY_MIN_BRIGHTNESS",
    "IMG_QUALITY_MAX_BRIGHTNESS",
    # OCR
    "OCR_DEFAULT_CONFIDENCE",
    # Inpainting
    "INPAINT_MIN_MASK_COVERAGE_PERCENT",
    "INPAINT_DEFAULT_DILATE_KERNEL",
]
